import os

configfile: "config.yaml"

INPUTS = config["inputs"]
ADMIN_LEVEL = config["admin_level"]

include: "rules/hazards/general.smk"
include: "rules/hazards/fathom.smk"
include: "rules/hazards/landslides.smk"

include: "rules/assets/points.smk"
include: "rules/assets/linestrings.smk"
include: "rules/assets/polygons.smk"

include: "rules/risk.smk"