name: ttra
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.12
  - geopandas
  - ipykernel
  - jupyter
  - networkx
  - nbstripout
  - numba
  - numpy
  - pandas
  - python-igraph
  - rasterio
  - scipy
  - shapely
  - snkit
  - tqdm
  - xarray
  - pip
  - gdal
  - seaborn
  - cartopy
  - pip:
      - -e .
      - -e ../oi-risk
      - nismod-snail
