import os

configfile: "config.yaml"

INPUTS = config["inputs"]
OUTPUTS = config["outputs"]
ADMIN_LEVEL = config["admin_level"]
REPROCESS_HAZARDS = bool(config["reprocess_hazards"])

# pre-processing rules for hazards
if REPROCESS_HAZARDS:
    include: "rules/hazards/fathom.smk"
    include: "rules/hazards/chaz.smk"
    include: "rules/hazards/landslides.smk"
    include: "rules/hazards.smk"

# main analysis rules
include: "rules/assets.smk"
include: "rules/risk.smk"
